missing user

diff --git a/.github/workflows/learn-github-actions.yaml b/.github/workflows/learn-github-actions.yaml
--- a/.github/workflows/learn-github-actions.yaml
+++ b/.github/workflows/learn-github-actions.yaml
@@ -41,22 +41,15 @@ To do it please create a new PR to the https://github.com/ockam-network/contribu
           set -x
           # Below attempt is to prevent following situation
           # https://github.community/t/github-actions-using-grep-when-no-lines-selected/126719
-          CVS_USER=$(grep ${{ env.USER }} contributors/CONTRIBUTORS.csv || echo '<MISSING>')
+          CVS_USER=$(grep --max-count=1 --only-matching ${{ env.USER }} contributors/CONTRIBUTORS.csv || echo '<MISSING>')
 
           if [[ "$CVS_USER" == "<MISSING>" ]]
           then
             echo "CLA_NOT_SIGNED=1" >> $GITHUB_ENV
           else
-            echo "CLA_NOT_SIGNED=1" >> $GITHUB_ENV
-            # CVS_USER=$(grep --max-count=1 --only-matching ${{ env.USER }} contributors/CONTRIBUTORS.csv)
-            # if [ "$CVS_USER" == "${{ env.USER }}" ]
-            # then 
-            #   echo "INFO: User $USER signed the CLA"
-            # else
-            #   echo "WARNING: something goes wrong"
-            # fi
+            echo "INFO: User $USER signed the CLA"
+            echo "CLA_NOT_SIGNED=0" >> $GITHUB_ENV
           fi
-          echo "CLA_NOT_SIGNED: ${{ env.CLA_NOT_SIGNED }} eee"
 
       - name: Prepare message
         if: env.CLA_NOT_SIGNED == 1
